using System.Collections.ObjectModel;
using System.IO;
using System.Text.Json;
using System.Windows;
using StoryboardDesigner.App.Models;
using StoryboardDesigner.App.ViewModels;
using Storyboard.Shared.GameServices.References;
using Storyboard.Shared.RuntimeContracts.Enums;
using WpfMessageBox = System.Windows.MessageBox;
using WpfMessageBoxButton = System.Windows.MessageBoxButton;
using WpfMessageBoxImage = System.Windows.MessageBoxImage;

namespace StoryboardDesigner.App.Views;

public partial class EventSubscriptionEditorDialog : Window
{
    private const string DefaultLane = "foreground";
    private const string DefaultOnMissingAction = "DiagnosticOnly";
    private const string EventSubscriptionSchemaRelativePath = "schemas\\runtime\\DtoContracts\\Core\\EventSubscription.core.schema.json";
    private const string EventPayloadManifestRelativePath = "Config\\event-payload.manifest.json";
    private const string ActionPayloadManifestRelativePath = "Config\\action-payload.manifest.json";
    private static readonly Lazy<IReadOnlyList<string>> LaneOptions = new(LoadLaneOptionsFromSchema);

    private readonly EventSubscriptionDefinition _entry;
    private readonly IReadOnlyList<string> _actionNameSuggestions;
    private readonly IReadOnlyList<string> _filterVariableSuggestions;
    private readonly IReadOnlyList<string> _anchorOptions;
    private readonly IReadOnlyList<GamePropertyChoiceItem> _filterVariableChoices;
    private readonly IReadOnlyList<ScopeObjectChoiceItem> _sourceScopeChoices;
    private readonly IReadOnlyList<string> _soundEffectKeySuggestions;
    private readonly IReadOnlyDictionary<string, IReadOnlyList<CommandActionType>> _actionNameToTypes;
    private bool _isInitializing;
    private bool _suppressSubscriptionNameTracking;
    private bool _isAutoGeneratedSubscriptionName;
    private string _lastAutoGeneratedSubscriptionName = string.Empty;

    public EventSubscriptionEditorDialog(
        EventSubscriptionDefinition initialEntry,
        IReadOnlyList<string>? eventKeyOptions = null,
        IReadOnlyList<string>? actionNameSuggestions = null,
        IReadOnlyList<string>? filterVariableSuggestions = null,
        IReadOnlyList<string>? onMissingActionOptions = null,
        IReadOnlyList<string>? anchorOptions = null,
        IReadOnlyList<GamePropertyChoiceItem>? filterVariableChoices = null,
        IReadOnlyList<ScopeObjectChoiceItem>? sourceScopeChoices = null,
        IReadOnlyList<string>? soundEffectKeySuggestions = null,
        IReadOnlyDictionary<string, IReadOnlyList<CommandActionType>>? actionNameToTypes = null)
    {
        InitializeComponent();
        _isInitializing = true;

        _entry = CloneEntry(initialEntry);
        _entry.ActionBindings ??= new List<EventActionBindingDefinition>();
        _entry.InputArgumentMappings ??= new List<EventInputArgumentMappingDefinition>();
        var initialEventKey = _entry.EventKey?.Trim() ?? string.Empty;
        EventKeyOptions = NormalizeSuggestions([
            ..(eventKeyOptions ?? Array.Empty<string>()),
            initialEventKey
        ]);
        _actionNameSuggestions = NormalizeSuggestions(actionNameSuggestions);
        _filterVariableSuggestions = NormalizeSuggestions(filterVariableSuggestions);
        _anchorOptions = NormalizeSuggestions(anchorOptions);
        _filterVariableChoices = (filterVariableChoices ?? Array.Empty<GamePropertyChoiceItem>())
            .Where(static choice => !string.IsNullOrWhiteSpace(choice.Value))
            .ToList();
        _sourceScopeChoices = NormalizeSourceScopeChoices(sourceScopeChoices);
        _soundEffectKeySuggestions = NormalizeSuggestions(soundEffectKeySuggestions);
        _actionNameToTypes = NormalizeActionTypeLookup(actionNameToTypes);

        ActionNameSuggestions = BuildActionNameOptionSet(_entry.ActionBindings, _actionNameSuggestions);
        FilterVariableSuggestions = _filterVariableSuggestions;
        OnMissingActionOptions = NormalizeTargetOptionSet(DefaultOnMissingAction, onMissingActionOptions, _entry.ActionBindings.Select(static binding => binding.Target?.OnMissingAction));

        EventKeyComboBox.ItemsSource = EventKeyOptions;
        LaneComboBox.ItemsSource = LaneOptionValues;
        DispatchComboBox.ItemsSource = DispatchOptions;
        SourceMatchModeComboBox.ItemsSource = SourceMatchModeOptions;
        SecondarySourceMatchModeComboBox.ItemsSource = SourceMatchModeOptions;
        DispatchComboBox.SelectedItem = _entry.DispatchDisposition;
        SourceMatchModeComboBox.SelectedItem = _entry.SubscriptionSourceMatchMode;
        SecondarySourceMatchModeComboBox.SelectedItem = _entry.SubscriptionSecondarySourceMatchMode;
        if (!string.IsNullOrWhiteSpace(initialEventKey))
        {
            EventKeyComboBox.SelectedItem = EventKeyOptions.FirstOrDefault(option =>
                string.Equals(option, initialEventKey, StringComparison.OrdinalIgnoreCase));
        }
        else
        {
            EventKeyComboBox.SelectedItem = null;
        }
        var initialSubscriptionName = _entry.SubscriptionName?.Trim() ?? string.Empty;
        SubscriptionNameTextBox.Text = initialSubscriptionName;
        if (!string.IsNullOrWhiteSpace(initialSubscriptionName)
            && string.Equals(initialSubscriptionName, EventKeyComboBox.Text?.Trim(), StringComparison.OrdinalIgnoreCase))
        {
            _isAutoGeneratedSubscriptionName = true;
            _lastAutoGeneratedSubscriptionName = initialSubscriptionName;
        }
        var resolvedLane = NormalizeLane(_entry.Lane);
        LaneComboBox.SelectedItem = resolvedLane;
        IsEnabledCheckBox.IsChecked = _entry.IsEnabled;
        VisibleWhenContainedCheckBox.IsChecked = _entry.SubscriptionVisibleWhenContained;
        SourceScopeIdTextBox.Text = _entry.SubscriptionSourceScopeNodeId?.ToString("D") ?? string.Empty;
        SecondarySourceScopeIdTextBox.Text = _entry.SubscriptionSecondarySourceScopeNodeId?.ToString("D") ?? string.Empty;
        UpdateSourceScopeFieldsEnabledState();

        foreach (var binding in _entry.ActionBindings)
        {
            binding.Condition ??= new EventBindingConditionDefinition();
            binding.Target ??= new EventBindingTargetDefinition();
            binding.Condition.Filters ??= new List<EventBindingFilterConditionDefinition>();
            binding.InputArgumentMappings ??= new List<EventInputArgumentMappingDefinition>();

            if (binding.InputArgumentMappings.Count == 0 && _entry.InputArgumentMappings.Count > 0)
            {
                binding.InputArgumentMappings = CloneInputArgumentMappings(_entry.InputArgumentMappings);
            }
        }

        BindingsDataGrid.ItemsSource = _entry.ActionBindings;
        if (_entry.ActionBindings.Count > 0)
        {
            BindingsDataGrid.SelectedIndex = 0;
        }

        RefreshFilterGrid();
        _isInitializing = false;
    }

    public EventSubscriptionDefinition Entry { get; private set; } = new();

    public IReadOnlyList<EventSubscriberDispatchDisposition> DispatchOptions { get; } =
        Enum.GetValues<EventSubscriberDispatchDisposition>();

    public IReadOnlyList<SubscriptionSourceMatchMode> SourceMatchModeOptions { get; } =
        Enum.GetValues<SubscriptionSourceMatchMode>();

    public IReadOnlyList<string> EventKeyOptions { get; }

    public IReadOnlyList<string> LaneOptionValues => LaneOptions.Value;

    public IReadOnlyList<RuntimeVariableQuantityEvaluationMode> QuantityModes { get; } =
        Enum.GetValues<RuntimeVariableQuantityEvaluationMode>()
            .Where(static mode => mode != RuntimeVariableQuantityEvaluationMode.SumOfResolvedCanPass)
            .ToList();

    public IReadOnlyList<RuntimeVariableComparisonOperator> ComparisonOperators { get; } =
        Enum.GetValues<RuntimeVariableComparisonOperator>();

    public IReadOnlyList<string> ActionNameSuggestions { get; }

    public IReadOnlyList<string> FilterVariableSuggestions { get; }

    public IReadOnlyList<string> OnMissingActionOptions { get; }

    private void BindingsDataGrid_OnSelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
    {
        RefreshFilterGrid();
    }

    private void AddBinding_OnClick(object sender, RoutedEventArgs e)
    {
        var nextOrder = _entry.ActionBindings.Count == 0
            ? 1
            : _entry.ActionBindings.Max(static binding => binding.Order) + 1;
        var binding = new EventActionBindingDefinition
        {
            Order = nextOrder,
            IsEnabled = true,
            Condition = new EventBindingConditionDefinition
            {
                QuantityEvaluationMode = RuntimeVariableQuantityEvaluationMode.AllResolvedMustPass
            },
            Target = new EventBindingTargetDefinition
            {
                ActionName = _actionNameSuggestions.FirstOrDefault() ?? "inspect",
                OnMissingAction = DefaultOnMissingAction,
                StopChainOnFailure = true
            },
            InputArgumentMappings = new List<EventInputArgumentMappingDefinition>()
        };

        _entry.ActionBindings.Add(binding);
        BindingsDataGrid.ItemsSource = null;
        BindingsDataGrid.ItemsSource = _entry.ActionBindings;
        BindingsDataGrid.SelectedItem = binding;
        BindingsDataGrid.ScrollIntoView(binding);
    }

    private void RemoveBinding_OnClick(object sender, RoutedEventArgs e)
    {
        if (BindingsDataGrid.SelectedItem is not EventActionBindingDefinition selectedBinding)
        {
            return;
        }

        _entry.ActionBindings.Remove(selectedBinding);
        BindingsDataGrid.ItemsSource = null;
        BindingsDataGrid.ItemsSource = _entry.ActionBindings;
        RefreshFilterGrid();
    }

    private void AddFilter_OnClick(object sender, RoutedEventArgs e)
    {
        var selectedBinding = GetSelectedBinding();
        if (selectedBinding is null)
        {
            return;
        }

        selectedBinding.Condition ??= new EventBindingConditionDefinition();
        selectedBinding.Condition.Filters ??= new List<EventBindingFilterConditionDefinition>();

        var filter = new EventBindingFilterConditionDefinition
        {
            VariableName = _filterVariableSuggestions.FirstOrDefault() ?? "action.trigger.isEventFired",
            Operator = RuntimeVariableComparisonOperator.Equals,
            ExpectedValue = "true"
        };

        selectedBinding.Condition.Filters.Add(filter);
        RefreshFilterGrid();
        FiltersDataGrid.SelectedItem = filter;
        FiltersDataGrid.ScrollIntoView(filter);
    }

    private void RemoveFilter_OnClick(object sender, RoutedEventArgs e)
    {
        var selectedBinding = GetSelectedBinding();
        if (selectedBinding is null || FiltersDataGrid.SelectedItem is not EventBindingFilterConditionDefinition selectedFilter)
        {
            return;
        }

        selectedBinding.Condition ??= new EventBindingConditionDefinition();
        selectedBinding.Condition.Filters ??= new List<EventBindingFilterConditionDefinition>();
        selectedBinding.Condition.Filters.Remove(selectedFilter);
        RefreshFilterGrid();
    }

    private void ChooseFilterVariable_OnClick(object sender, RoutedEventArgs e)
    {
        var selectedBinding = GetSelectedBinding();
        if (selectedBinding is null || FiltersDataGrid.SelectedItem is not EventBindingFilterConditionDefinition selectedFilter)
        {
            return;
        }

        var currentEventKey = EventKeyComboBox.Text?.Trim() ?? string.Empty;
        var knownPayloadMappings = LoadEventPayloadMappingsForEventKey(currentEventKey);
        var anchorSubProperties = LoadAnchorSubPropertiesFromManifest();

        var dialog = new EventBindingVariableAssistDialog(
            _anchorOptions,
            knownPayloadMappings,
            anchorSubProperties,
            LoadActionOutputVariablesForBindingAction(selectedBinding),
            _filterVariableChoices,
            selectedFilter.VariableName)
        {
            Owner = this
        };

        if (!string.IsNullOrWhiteSpace(currentEventKey))
        {
            dialog.Title = $"Choose Event Filter Variable - {currentEventKey}";
        }

        if (dialog.ShowDialog() != true || string.IsNullOrWhiteSpace(dialog.SelectedVariablePath))
        {
            return;
        }

        selectedFilter.VariableName = dialog.SelectedVariablePath.Trim();
        FiltersDataGrid.Items.Refresh();
    }

    private void OpenInputMappings_OnClick(object sender, RoutedEventArgs e)
    {
        var selectedBinding = (sender as FrameworkElement)?.DataContext as EventActionBindingDefinition
            ?? GetSelectedBinding();
        if (selectedBinding is null)
        {
            return;
        }

        selectedBinding.InputArgumentMappings ??= new List<EventInputArgumentMappingDefinition>();

        var dialog = new EventInputArgumentMappingsDialog(
            EventKeyComboBox.Text?.Trim() ?? string.Empty,
            selectedBinding.InputArgumentMappings,
            _soundEffectKeySuggestions)
        {
            Owner = this
        };

        if (dialog.ShowDialog() != true)
        {
            return;
        }

        selectedBinding.InputArgumentMappings = CloneInputArgumentMappings(dialog.Mappings);

        // Preserve compatibility by mirroring the selected binding's mappings into the legacy subscription field.
        _entry.InputArgumentMappings = CloneInputArgumentMappings(selectedBinding.InputArgumentMappings);
    }

    private static IReadOnlyList<KeyValuePair<string, string>> LoadEventPayloadMappingsForEventKey(string eventKey)
    {
        var normalizedEventKey = eventKey?.Trim() ?? string.Empty;
        if (string.IsNullOrWhiteSpace(normalizedEventKey))
        {
            return Array.Empty<KeyValuePair<string, string>>();
        }

        var manifestPath = Path.Combine(AppContext.BaseDirectory, EventPayloadManifestRelativePath);
        if (!File.Exists(manifestPath))
        {
            return Array.Empty<KeyValuePair<string, string>>();
        }

        try
        {
            using var stream = File.OpenRead(manifestPath);
            using var document = JsonDocument.Parse(stream);
            if (!document.RootElement.TryGetProperty("events", out var eventsElement)
                || eventsElement.ValueKind != JsonValueKind.Array)
            {
                return Array.Empty<KeyValuePair<string, string>>();
            }

            var mappings = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var eventElement in eventsElement.EnumerateArray())
            {
                if (!eventElement.TryGetProperty("eventKey", out var eventKeyElement)
                    || eventKeyElement.ValueKind != JsonValueKind.String)
                {
                    continue;
                }

                var manifestEventKey = eventKeyElement.GetString()?.Trim() ?? string.Empty;
                if (!string.Equals(manifestEventKey, normalizedEventKey, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                if (!eventElement.TryGetProperty("payloadMappings", out var mappingsElement)
                    || mappingsElement.ValueKind != JsonValueKind.Array)
                {
                    continue;
                }

                foreach (var mappingElement in mappingsElement.EnumerateArray())
                {
                    if (!mappingElement.TryGetProperty("payloadKey", out var payloadKeyElement)
                        || payloadKeyElement.ValueKind != JsonValueKind.String)
                    {
                        continue;
                    }

                    if (!mappingElement.TryGetProperty("sourcePath", out var sourcePathElement)
                        || sourcePathElement.ValueKind != JsonValueKind.String)
                    {
                        continue;
                    }

                    var payloadKey = payloadKeyElement.GetString()?.Trim() ?? string.Empty;
                    var sourcePath = sourcePathElement.GetString()?.Trim() ?? string.Empty;
                    if (!string.IsNullOrWhiteSpace(payloadKey)
                        && !string.IsNullOrWhiteSpace(sourcePath)
                        && !mappings.ContainsKey(payloadKey))
                    {
                        mappings[payloadKey] = sourcePath;
                    }
                }
            }

            return mappings
                .OrderBy(static pair => pair.Key, StringComparer.OrdinalIgnoreCase)
                .Select(static pair => new KeyValuePair<string, string>(pair.Key, pair.Value))
                .ToList();
        }
        catch
        {
            return Array.Empty<KeyValuePair<string, string>>();
        }
    }

    private static IReadOnlyList<EventBindingVariableAssistDialog.AnchorSubPropertyDefinition> LoadAnchorSubPropertiesFromManifest()
    {
        try
        {
            var output = new List<EventBindingVariableAssistDialog.AnchorSubPropertyDefinition>();
            foreach (var anchor in new RuntimeSessionAnchorManifestReader().Load().Anchors)
            {
                var anchorKey = anchor.AnchorKey?.Trim() ?? string.Empty;
                if (string.IsNullOrWhiteSpace(anchorKey))
                {
                    continue;
                }

                foreach (var subProperty in anchor.SupportedSubProperties)
                {
                    var propertyKey = subProperty.PropertyKey?.Trim() ?? string.Empty;
                    if (string.IsNullOrWhiteSpace(propertyKey))
                    {
                        continue;
                    }

                    var sourcePath = subProperty.SourcePath?.Trim() ?? string.Empty;
                    var expectedScopeType = string.IsNullOrWhiteSpace(subProperty.ExpectedScopeType)
                        ? "Unknown"
                        : subProperty.ExpectedScopeType.Trim();

                    output.Add(new EventBindingVariableAssistDialog.AnchorSubPropertyDefinition(
                        anchorKey,
                        propertyKey,
                        sourcePath,
                        expectedScopeType));
                }
            }

            return output;
        }
        catch
        {
            return Array.Empty<EventBindingVariableAssistDialog.AnchorSubPropertyDefinition>();
        }
    }

    private IReadOnlyList<EventBindingVariableAssistDialog.ActionOutputVariableDefinition> LoadActionOutputVariablesForBindingAction(
        EventActionBindingDefinition binding)
    {
        var actionName = binding.Target?.ActionName?.Trim() ?? string.Empty;
        if (string.IsNullOrWhiteSpace(actionName)
            || !_actionNameToTypes.TryGetValue(actionName, out var actionTypes)
            || actionTypes.Count == 0)
        {
            return Array.Empty<EventBindingVariableAssistDialog.ActionOutputVariableDefinition>();
        }

        return LoadActionOutputVariableCatalogFromManifest(actionTypes);
    }

    private static IReadOnlyList<EventBindingVariableAssistDialog.ActionOutputVariableDefinition> LoadActionOutputVariableCatalogFromManifest(
        IReadOnlyList<CommandActionType> actionTypes)
    {
        var actionTypeNames = actionTypes
            .Select(static actionType => actionType.ToString())
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        if (actionTypeNames.Count == 0)
        {
            return Array.Empty<EventBindingVariableAssistDialog.ActionOutputVariableDefinition>();
        }

        var manifestPath = Path.Combine(AppContext.BaseDirectory, ActionPayloadManifestRelativePath);
        if (!File.Exists(manifestPath))
        {
            return Array.Empty<EventBindingVariableAssistDialog.ActionOutputVariableDefinition>();
        }

        try
        {
            using var stream = File.OpenRead(manifestPath);
            using var document = JsonDocument.Parse(stream);

            if (!document.RootElement.TryGetProperty("perActionTypeCatalog", out var perActionCatalog)
                || perActionCatalog.ValueKind != JsonValueKind.Array)
            {
                return Array.Empty<EventBindingVariableAssistDialog.ActionOutputVariableDefinition>();
            }

            var results = new List<EventBindingVariableAssistDialog.ActionOutputVariableDefinition>();

            foreach (var actionCatalog in perActionCatalog.EnumerateArray())
            {
                if (!actionCatalog.TryGetProperty("actionType", out var actionTypeElement)
                    || actionTypeElement.ValueKind != JsonValueKind.String)
                {
                    continue;
                }

                var actionTypeText = actionTypeElement.GetString()?.Trim() ?? string.Empty;
                if (!actionTypeNames.Contains(actionTypeText)
                    || !Enum.TryParse<CommandActionType>(actionTypeText, ignoreCase: true, out var actionType))
                {
                    continue;
                }

                if (!actionCatalog.TryGetProperty("actionOutputVariableCatalog", out var outputCatalog)
                    || outputCatalog.ValueKind != JsonValueKind.Array)
                {
                    continue;
                }

                foreach (var outputEntry in outputCatalog.EnumerateArray())
                {
                    var key = ReadTrimmedString(outputEntry, "actionOutputVariableKey");
                    if (string.IsNullOrWhiteSpace(key))
                    {
                        continue;
                    }

                    results.Add(new EventBindingVariableAssistDialog.ActionOutputVariableDefinition(
                        actionType,
                        key,
                        ReadTrimmedString(outputEntry, "description"),
                        ReadTrimmedString(outputEntry, "valueType"),
                        ReadTrimmedString(outputEntry, "notes")));
                }
            }

            return results
                .GroupBy(static item => $"{item.ActionType}|{item.ActionOutputVariableKey}", StringComparer.OrdinalIgnoreCase)
                .Select(static group => group.First())
                .OrderBy(static item => item.ActionType.ToString(), StringComparer.OrdinalIgnoreCase)
                .ThenBy(static item => item.ActionOutputVariableKey, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }
        catch
        {
            return Array.Empty<EventBindingVariableAssistDialog.ActionOutputVariableDefinition>();
        }
    }

    private void Save_OnClick(object sender, RoutedEventArgs e)
    {
        _entry.EventKey = (EventKeyComboBox.SelectedItem as string)?.Trim() ?? string.Empty;
        _entry.SubscriptionName = ResolveSubscriptionDisplayName(
            SubscriptionNameTextBox.Text?.Trim() ?? string.Empty,
            _entry.EventKey);
        _entry.Lane = NormalizeLane(LaneComboBox.SelectedItem as string);
        _entry.IsEnabled = IsEnabledCheckBox.IsChecked == true;
        _entry.SubscriptionVisibleWhenContained = VisibleWhenContainedCheckBox.IsChecked == true;
        _entry.DispatchDisposition = DispatchComboBox.SelectedItem is EventSubscriberDispatchDisposition dispatch
            ? dispatch
            : EventSubscriberDispatchDisposition.bubble;
        _entry.SubscriptionSourceMatchMode = SourceMatchModeComboBox.SelectedItem is SubscriptionSourceMatchMode sourceMatchMode
            ? sourceMatchMode
            : SubscriptionSourceMatchMode.AnySource;

        _entry.SubscriptionSecondarySourceMatchMode = SecondarySourceMatchModeComboBox.SelectedItem is SubscriptionSourceMatchMode secondarySourceMatchMode
            ? secondarySourceMatchMode
            : SubscriptionSourceMatchMode.AnySource;

        var sourceScopeIdText = SourceScopeIdTextBox.Text?.Trim() ?? string.Empty;
        if (string.IsNullOrWhiteSpace(sourceScopeIdText))
        {
            _entry.SubscriptionSourceScopeNodeId = null;
        }
        else if (Guid.TryParse(sourceScopeIdText, out var sourceScopeId) && sourceScopeId != Guid.Empty)
        {
            _entry.SubscriptionSourceScopeNodeId = sourceScopeId;
        }
        else
        {
            WpfMessageBox.Show(
                this,
                "Source Scope Id must be a valid non-empty GUID when provided.",
                "Event Subscription",
                WpfMessageBoxButton.OK,
                WpfMessageBoxImage.Information);
            return;
        }

        var secondarySourceScopeIdText = SecondarySourceScopeIdTextBox.Text?.Trim() ?? string.Empty;
        if (string.IsNullOrWhiteSpace(secondarySourceScopeIdText))
        {
            _entry.SubscriptionSecondarySourceScopeNodeId = null;
        }
        else if (Guid.TryParse(secondarySourceScopeIdText, out var secondarySourceScopeId) && secondarySourceScopeId != Guid.Empty)
        {
            _entry.SubscriptionSecondarySourceScopeNodeId = secondarySourceScopeId;
        }
        else
        {
            WpfMessageBox.Show(
                this,
                "Secondary Source Scope Id must be a valid non-empty GUID when provided.",
                "Event Subscription",
                WpfMessageBoxButton.OK,
                WpfMessageBoxImage.Information);
            return;
        }

        if (_entry.Id == Guid.Empty)
        {
            _entry.Id = Guid.NewGuid();
        }

        var errors = ValidateEntry(_entry);
        if (errors.Count > 0)
        {
            WpfMessageBox.Show(
                this,
                string.Join(Environment.NewLine, errors),
                "Event Subscription",
                WpfMessageBoxButton.OK,
                WpfMessageBoxImage.Information);
            return;
        }

        Entry = CloneEntry(_entry);
        DialogResult = true;
    }

    private void Cancel_OnClick(object sender, RoutedEventArgs e)
    {
        DialogResult = false;
    }

    private void SourceMatchModeComboBox_OnSelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
    {
        UpdateSourceScopeFieldsEnabledState();
    }

    private void SecondarySourceMatchModeComboBox_OnSelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
    {
        UpdateSourceScopeFieldsEnabledState();
    }

    private void EventKeyComboBox_OnSelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
    {
        TryAutoPopulateSubscriptionNameFromEventKey();
    }

    private void EventKeyComboBox_OnLostKeyboardFocus(object sender, System.Windows.Input.KeyboardFocusChangedEventArgs e)
    {
        TryAutoPopulateSubscriptionNameFromEventKey();
    }

    private void SubscriptionNameTextBox_OnTextChanged(object sender, System.Windows.Controls.TextChangedEventArgs e)
    {
        if (_isInitializing || _suppressSubscriptionNameTracking)
        {
            return;
        }

        var current = SubscriptionNameTextBox.Text?.Trim() ?? string.Empty;
        _isAutoGeneratedSubscriptionName = !string.IsNullOrWhiteSpace(_lastAutoGeneratedSubscriptionName)
            && string.Equals(current, _lastAutoGeneratedSubscriptionName, StringComparison.OrdinalIgnoreCase);
    }

    private void TryAutoPopulateSubscriptionNameFromEventKey()
    {
        if (_isInitializing)
        {
            return;
        }

        var selectedEventKey = EventKeyComboBox.Text?.Trim() ?? string.Empty;
        if (string.IsNullOrWhiteSpace(selectedEventKey))
        {
            return;
        }

        var currentName = SubscriptionNameTextBox.Text?.Trim() ?? string.Empty;
        if (!string.IsNullOrWhiteSpace(currentName) && !_isAutoGeneratedSubscriptionName)
        {
            return;
        }

        if (string.Equals(currentName, selectedEventKey, StringComparison.OrdinalIgnoreCase))
        {
            _isAutoGeneratedSubscriptionName = true;
            _lastAutoGeneratedSubscriptionName = selectedEventKey;
            return;
        }

        _suppressSubscriptionNameTracking = true;
        try
        {
            SubscriptionNameTextBox.Text = selectedEventKey;
        }
        finally
        {
            _suppressSubscriptionNameTracking = false;
        }

        _isAutoGeneratedSubscriptionName = true;
        _lastAutoGeneratedSubscriptionName = selectedEventKey;
    }

    private void ChooseSourceScope_OnClick(object sender, RoutedEventArgs e)
    {
        ChooseScopeIdIntoTextBox(SourceScopeIdTextBox, "Choose Source Scope Id", SourceMatchModeComboBox.SelectedItem as SubscriptionSourceMatchMode?);
    }

    private void ClearSourceScope_OnClick(object sender, RoutedEventArgs e)
    {
        SourceScopeIdTextBox.Text = string.Empty;
    }

    private void ChooseSecondarySourceScope_OnClick(object sender, RoutedEventArgs e)
    {
        ChooseScopeIdIntoTextBox(SecondarySourceScopeIdTextBox, "Choose Secondary Source Scope Id", SecondarySourceMatchModeComboBox.SelectedItem as SubscriptionSourceMatchMode?);
    }

    private void ClearSecondarySourceScope_OnClick(object sender, RoutedEventArgs e)
    {
        SecondarySourceScopeIdTextBox.Text = string.Empty;
    }

    private void ChooseScopeIdIntoTextBox(
        System.Windows.Controls.TextBox targetTextBox,
        string title,
        SubscriptionSourceMatchMode? selectedMode)
    {
        if (_sourceScopeChoices.Count == 0)
        {
            WpfMessageBox.Show(
                this,
                "No scope choices are available for this context.",
                "Event Subscription",
                WpfMessageBoxButton.OK,
                WpfMessageBoxImage.Information);
            return;
        }

        var selectedKey = targetTextBox.Text?.Trim();
        if (string.IsNullOrWhiteSpace(selectedKey)
            || !Guid.TryParse(selectedKey, out var parsed)
            || parsed == Guid.Empty)
        {
            selectedKey = null;
        }
        else
        {
            selectedKey = parsed.ToString("D");
        }

        var dialog = new ScopeObjectChooserDialog(_sourceScopeChoices, title, expectedScope: null, selectedKey)
        {
            Owner = this
        };

        if (dialog.ShowDialog() != true || string.IsNullOrWhiteSpace(dialog.SelectedKey))
        {
            return;
        }

        targetTextBox.Text = dialog.SelectedKey.Trim();

        if (selectedMode is SubscriptionSourceMatchMode mode
            && mode != SubscriptionSourceMatchMode.ExplicitSourceId)
        {
            WpfMessageBox.Show(
                this,
                "Source Match is not set to ExplicitSourceId. The selected id will only apply when match mode is ExplicitSourceId.",
                "Event Subscription",
                WpfMessageBoxButton.OK,
                WpfMessageBoxImage.Information);
        }
    }

    private void UpdateSourceScopeFieldsEnabledState()
    {
        var sourceMatchMode = SourceMatchModeComboBox.SelectedItem is SubscriptionSourceMatchMode selectedMode
            ? selectedMode
            : SubscriptionSourceMatchMode.AnySource;
        var isPrimaryExplicit = sourceMatchMode == SubscriptionSourceMatchMode.ExplicitSourceId;
        SourceScopeIdTextBox.IsEnabled = isPrimaryExplicit;
        ChooseSourceScopeButton.IsEnabled = isPrimaryExplicit;
        ClearSourceScopeButton.IsEnabled = isPrimaryExplicit;

        var secondarySourceMatchMode = SecondarySourceMatchModeComboBox.SelectedItem is SubscriptionSourceMatchMode selectedSecondaryMode
            ? selectedSecondaryMode
            : SubscriptionSourceMatchMode.AnySource;
        var isSecondaryExplicit = secondarySourceMatchMode == SubscriptionSourceMatchMode.ExplicitSourceId;
        SecondarySourceScopeIdTextBox.IsEnabled = isSecondaryExplicit;
        ChooseSecondarySourceScopeButton.IsEnabled = isSecondaryExplicit;
        ClearSecondarySourceScopeButton.IsEnabled = isSecondaryExplicit;
    }

    private EventActionBindingDefinition? GetSelectedBinding()
    {
        if (BindingsDataGrid.SelectedItem is EventActionBindingDefinition selected)
        {
            return selected;
        }

        var fallback = _entry.ActionBindings.FirstOrDefault();
        if (fallback is not null)
        {
            BindingsDataGrid.SelectedItem = fallback;
        }

        return fallback;
    }

    private void RefreshFilterGrid()
    {
        var selectedBinding = GetSelectedBinding();
        if (selectedBinding is null)
        {
            FiltersDataGrid.ItemsSource = null;
            return;
        }

        selectedBinding.Condition ??= new EventBindingConditionDefinition();
        selectedBinding.Condition.Filters ??= new List<EventBindingFilterConditionDefinition>();
        // Filters are backed by List<T>; force a hard rebind so consecutive adds always render.
        FiltersDataGrid.ItemsSource = null;
        FiltersDataGrid.ItemsSource = selectedBinding.Condition.Filters;

        if (selectedBinding.Condition.Filters.Count > 0)
        {
            FiltersDataGrid.SelectedIndex = 0;
        }
    }

    private static List<string> ValidateEntry(EventSubscriptionDefinition entry)
    {
        var errors = new List<string>();
        if (string.IsNullOrWhiteSpace(entry.EventKey))
        {
            errors.Add("Event Key is required.");
        }

        var bindings = entry.ActionBindings ?? new List<EventActionBindingDefinition>();
        var duplicateOrders = bindings
            .GroupBy(static binding => binding.Order)
            .Where(static group => group.Count() > 1)
            .Select(static group => group.Key)
            .OrderBy(static order => order)
            .ToList();

        foreach (var duplicateOrder in duplicateOrders)
        {
            errors.Add($"Duplicate binding order '{duplicateOrder}'.");
        }

        for (var bindingIndex = 0; bindingIndex < bindings.Count; bindingIndex++)
        {
            var binding = bindings[bindingIndex];
            if (string.IsNullOrWhiteSpace(binding.Target?.ActionName))
            {
                errors.Add($"Binding {bindingIndex + 1}: Action Name is required.");
            }

            var filters = binding.Condition?.Filters ?? new List<EventBindingFilterConditionDefinition>();
            for (var filterIndex = 0; filterIndex < filters.Count; filterIndex++)
            {
                if (!string.IsNullOrWhiteSpace(filters[filterIndex].VariableName))
                {
                    continue;
                }

                errors.Add($"Binding {bindingIndex + 1}, Filter {filterIndex + 1}: Variable Name is required.");
            }
        }

        return errors;
    }

    private static EventSubscriptionDefinition CloneEntry(EventSubscriptionDefinition source)
    {
        var legacyMappings = CloneInputArgumentMappings(source.InputArgumentMappings ?? new List<EventInputArgumentMappingDefinition>());
        return new EventSubscriptionDefinition
        {
            Id = source.Id,
            EventKey = source.EventKey,
            SubscriptionName = ResolveSubscriptionDisplayName(source),
            IsEnabled = source.IsEnabled,
            Lane = source.Lane,
            DispatchDisposition = source.DispatchDisposition,
            SubscriptionVisibleWhenContained = source.SubscriptionVisibleWhenContained,
            SubscriptionSourceMatchMode = source.SubscriptionSourceMatchMode,
            SubscriptionSourceScopeNodeId = source.SubscriptionSourceScopeNodeId,
            SubscriptionSecondarySourceMatchMode = source.SubscriptionSecondarySourceMatchMode,
            SubscriptionSecondarySourceScopeNodeId = source.SubscriptionSecondarySourceScopeNodeId,
            InputArgumentMappings = legacyMappings,
            ActionBindings = (source.ActionBindings ?? new List<EventActionBindingDefinition>())
                .Select(binding =>
                {
                    var bindingMappings = CloneInputArgumentMappings(binding.InputArgumentMappings ?? new List<EventInputArgumentMappingDefinition>());
                    if (bindingMappings.Count == 0 && legacyMappings.Count > 0)
                    {
                        bindingMappings = CloneInputArgumentMappings(legacyMappings);
                    }

                    return new EventActionBindingDefinition
                    {
                        Order = binding.Order,
                        IsEnabled = binding.IsEnabled,
                        Target = new EventBindingTargetDefinition
                        {
                            ActionName = binding.Target?.ActionName ?? string.Empty,
                            OnMissingAction = binding.Target?.OnMissingAction ?? DefaultOnMissingAction,
                            StopChainOnFailure = binding.Target?.StopChainOnFailure ?? true
                        },
                        Condition = new EventBindingConditionDefinition
                        {
                            QuantityEvaluationMode = binding.Condition?.QuantityEvaluationMode
                                ?? RuntimeVariableQuantityEvaluationMode.AllResolvedMustPass,
                            Filters = (binding.Condition?.Filters ?? new List<EventBindingFilterConditionDefinition>())
                                .Select(static filter => new EventBindingFilterConditionDefinition
                                {
                                    VariableName = filter.VariableName,
                                    Operator = filter.Operator,
                                    ExpectedValue = filter.ExpectedValue
                                })
                                .ToList()
                        },
                        InputArgumentMappings = bindingMappings
                    };
                })
                .ToList()
        };
    }

    private static List<EventInputArgumentMappingDefinition> CloneInputArgumentMappings(
        IReadOnlyList<EventInputArgumentMappingDefinition> source)
    {
        return source
            .Select(static mapping => mapping.CloneNormalized())
            .Where(static mapping =>
                mapping.SourceType == EventInputArgumentMappingSourceType.ConstantValue
                    ? !string.IsNullOrWhiteSpace(mapping.OutputActionPayloadArgKey)
                    : !string.IsNullOrWhiteSpace(mapping.InputEventPaylloadArgKey))
            .ToList();
    }

    private static string ResolveSubscriptionDisplayName(EventSubscriptionDefinition entry)
    {
        return ResolveSubscriptionDisplayName(entry.SubscriptionName, entry.EventKey);
    }

    private static string ResolveSubscriptionDisplayName(string? subscriptionName, string? eventKey)
    {
        var normalizedName = subscriptionName?.Trim() ?? string.Empty;
        if (!string.IsNullOrWhiteSpace(normalizedName))
        {
            return normalizedName;
        }

        return eventKey?.Trim() ?? string.Empty;
    }

    private static IReadOnlyList<string> NormalizeSuggestions(IReadOnlyList<string>? source)
    {
        return (source ?? Array.Empty<string>())
            .Select(static item => item?.Trim() ?? string.Empty)
            .Where(static item => !string.IsNullOrWhiteSpace(item))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static item => item, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static IReadOnlyList<ScopeObjectChoiceItem> NormalizeSourceScopeChoices(
        IReadOnlyList<ScopeObjectChoiceItem>? source)
    {
        return (source ?? Array.Empty<ScopeObjectChoiceItem>())
            .Where(static item =>
                !string.IsNullOrWhiteSpace(item.Key)
                && Guid.TryParse(item.Key.Trim(), out var parsed)
                && parsed != Guid.Empty)
            .GroupBy(static item => item.Key.Trim(), StringComparer.OrdinalIgnoreCase)
            .Select(static group => group.First())
            .OrderBy(static item => item.DisplayName, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static IReadOnlyDictionary<string, IReadOnlyList<CommandActionType>> NormalizeActionTypeLookup(
        IReadOnlyDictionary<string, IReadOnlyList<CommandActionType>>? source)
    {
        var lookup = new Dictionary<string, IReadOnlyList<CommandActionType>>(StringComparer.OrdinalIgnoreCase);
        if (source is null)
        {
            return lookup;
        }

        foreach (var pair in source)
        {
            var actionName = pair.Key?.Trim() ?? string.Empty;
            if (string.IsNullOrWhiteSpace(actionName))
            {
                continue;
            }

            lookup[actionName] = (pair.Value ?? Array.Empty<CommandActionType>())
                .Distinct()
                .OrderBy(static actionType => actionType.ToString(), StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        return lookup;
    }

    private static string ReadTrimmedString(JsonElement element, string propertyName)
    {
        if (!element.TryGetProperty(propertyName, out var value)
            || value.ValueKind != JsonValueKind.String)
        {
            return string.Empty;
        }

        return value.GetString()?.Trim() ?? string.Empty;
    }

    private static IReadOnlyList<string> NormalizeTargetOptionSet(
        string defaultValue,
        IReadOnlyList<string>? preferredValues,
        IEnumerable<string?> authoredValues)
    {
        var values = new List<string> { defaultValue };
        values.AddRange(preferredValues ?? Array.Empty<string>());
        values.AddRange(authoredValues.Where(static value => !string.IsNullOrWhiteSpace(value))!);

        return values
            .Select(static value => value?.Trim() ?? string.Empty)
            .Where(static value => !string.IsNullOrWhiteSpace(value))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static value => value, StringComparer.OrdinalIgnoreCase)
            .OrderBy(value => string.Equals(value, defaultValue, StringComparison.OrdinalIgnoreCase) ? 0 : 1)
            .ToList();
    }

    private static IReadOnlyList<string> BuildActionNameOptionSet(
        IEnumerable<EventActionBindingDefinition> bindings,
        IReadOnlyList<string> preferredValues)
    {
        var values = new List<string>();
        values.AddRange(preferredValues);
        values.AddRange(bindings
            .Select(static binding => binding.Target?.ActionName)
            .Where(static value => !string.IsNullOrWhiteSpace(value))
            .Select(static value => value!));
        values.Add("inspect");

        return values
            .Select(static value => value?.Trim() ?? string.Empty)
            .Where(static value => !string.IsNullOrWhiteSpace(value))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static value => value, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static string NormalizeLane(string? lane)
    {
        var normalized = lane?.Trim() ?? string.Empty;
        if (LaneOptions.Value.Any(option => string.Equals(option, normalized, StringComparison.OrdinalIgnoreCase)))
        {
            return LaneOptions.Value.First(option => string.Equals(option, normalized, StringComparison.OrdinalIgnoreCase));
        }

        return DefaultLane;
    }

    private static IReadOnlyList<string> LoadLaneOptionsFromSchema()
    {
        var fallback = new List<string> { "foreground", "background" };
        var schemaPath = Path.Combine(AppContext.BaseDirectory, EventSubscriptionSchemaRelativePath);
        if (!File.Exists(schemaPath))
        {
            return fallback;
        }

        try
        {
            using var stream = File.OpenRead(schemaPath);
            using var document = JsonDocument.Parse(stream);

            if (!document.RootElement.TryGetProperty("properties", out var properties)
                || properties.ValueKind != JsonValueKind.Object
                || !properties.TryGetProperty("lane", out var lane)
                || lane.ValueKind != JsonValueKind.Object
                || !lane.TryGetProperty("enum", out var enumValues)
                || enumValues.ValueKind != JsonValueKind.Array)
            {
                return fallback;
            }

            var values = enumValues
                .EnumerateArray()
                .Where(static element => element.ValueKind == JsonValueKind.String)
                .Select(static element => element.GetString()?.Trim() ?? string.Empty)
                .Where(static value => !string.IsNullOrWhiteSpace(value))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();

            return values.Count > 0 ? values : fallback;
        }
        catch
        {
            return fallback;
        }
    }
}
