// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file AreaDto_contract.schema.json.
///
/// Represents an area in game play, i.e. a set of related rooms. This is a core contract that is
/// used by both the designer and runtime.
///
/// The designer representation of an area in game play uses the TraversalConnection bidirectional
/// construct to represent and manage travel.
/// </summary>
internal sealed partial class AreaDto : DesignerScopeNodeDtoBase
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.AreaAdjacencyMode AdjacencyMode { get; set; } = ContractEnums.AreaAdjacencyMode.FourDirectional;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Guid? StartingRoomId { get; set; }

    public List<Guid> RoomIds { get; set; } = new();

    public List<RoomPlacementDto> RoomPlacements { get; set; } = new();

    public List<TraversalConnectionDto> TraversalConnections { get; set; } = new();

}
