// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file CommandActionDto_contract.schema.json.
/// </summary>
internal sealed partial class CommandActionDto
{
    public Guid Id { get; set; }

    public string Name { get; set; } = string.Empty;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ProjectCommandActionPayloadBaseDto? Payload { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.CommandActionType ActionType { get; set; } = ContractEnums.CommandActionType.EchoMessage;

    public bool NoVerbLinkage { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? VerbListText { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? Verbs { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Direction { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, string>? OutcomeMessageMap { get; set; }

    /// <summary>
    /// Optional per-result-code sound cue mappings. Keys are result-code tokens and values are
    /// ordered cue lists.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, List<OutcomeSoundEffectCueDto>>? OutcomeSoundEffectsMap { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.ChildCommandForwardingMode ChildCommandForwardingMode { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.SimilarChildDispatchMode? SimilarChildDispatchMode { get; set; } = ContractEnums.SimilarChildDispatchMode.SingleMatchingChild;

}
