// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file CountryDto_contract.schema.json.
///
/// Shared Country contract members used by runtime and designer DTO wrappers.
/// </summary>
internal sealed partial class CountryDto : DesignerScopeNodeDtoBase
{
    public string StartingAreaName { get; set; } = string.Empty;

    public List<Guid> AreaIds { get; set; } = new();

}
