// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// DesignerScopeNodeDtoBase_contract.schema.json.
/// </summary>
internal abstract partial class DesignerScopeNodeDtoBase
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.ScopeNodeKind ScopeKind { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<Guid>? BaseObjectIds { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<Guid>? GameObjectIds { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<Guid>? ProcedureIds { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<GamePropertyDefinitionDto>? GameProperties { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? AdditionalVerbs { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? AdditionalDirectionals { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<DirectionalTraversalMappingDto>? AdditionalDirectionalTraversalMappings { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<CommandActionDto>? AvailableGameActions { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ProjectEventSubscriptionDto>? EventSubscriptions { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ProjectTimerDefinitionDto>? TimerDefinitions { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<SoundEffectLibraryEntryDto>? SoundEffectLibraryEntries { get; set; }

}
