// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// GamePropertyDefinitionDto_contract.schema.json.
/// </summary>
internal sealed partial class GamePropertyDefinitionDto
{
    public Guid Id { get; set; }

    public string Name { get; set; } = string.Empty;

    public string DefaultValue { get; set; } = string.Empty;

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.GamePropertyValueRestriction ValueRestriction { get; set; } = ContractEnums.GamePropertyValueRestriction.Unrestricted;

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.GamePropertyLifetime Lifetime { get; set; } = ContractEnums.GamePropertyLifetime.Singleton;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Guid? SharedVariableId { get; set; }

}
