// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// OutcomeSoundEffectCueDto_contract.schema.json.
///
/// Binds a playable sound effect to an action result code outcome.
/// </summary>
internal sealed partial class OutcomeSoundEffectCueDto
{
    /// <summary>
    /// Required reference to a SoundEffectLibraryEntry by immutable GUID.
    /// </summary>
    public Guid SoundEffectId { get; set; }

    /// <summary>
    /// Optional authoring hint for diagnostics and readability; runtime resolution should use
    /// soundEffectId.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SoundEffectKeyHint { get; set; }

    /// <summary>
    /// When false, preserves authored mapping while preventing playback for this cue.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Enabled { get; set; } = true;

    /// <summary>
    /// Author-defined behavior for this cue when delivery is late relative to its originating
    /// emission.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.PresentationCueLateDeliveryPolicy? LateDeliveryPolicy { get; set; } = ContractEnums.PresentationCueLateDeliveryPolicy.PlayIfLate;

    /// <summary>
    /// Optional late-delivery window in milliseconds. When provided, runtime may drop cues older
    /// than this threshold according to policy.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? MaxLateMs { get; set; }

}
