// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file PhaseNodeDto_contract.schema.json.
///
/// Shared phase-node contract members used by runtime and designer DTO wrappers.
/// </summary>
internal sealed partial class PhaseNodeDto : DesignerScopeNodeDtoBase
{
    /// <summary>
    /// Stable producer-owned key used for SetPhase targeting and diagnostics.
    /// </summary>
    public string PhaseKey { get; set; } = string.Empty;

    /// <summary>
    /// Hierarchy tier for this phase node.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.PhaseTier PhaseTier { get; set; }

    /// <summary>
    /// Concise host-facing phase display label.
    /// </summary>
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>
    /// Optional narrative title shown at phase transitions.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Title { get; set; }

    /// <summary>
    /// Optional presentation cue effect key used when presenting title text.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TitlePresentationCueEffectKey { get; set; }

    /// <summary>
    /// Optional narrative prologue shown at phase transitions.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Prologue { get; set; }

    /// <summary>
    /// Optional presentation cue effect key used when presenting prologue text.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ProloguePresentationCueEffectKey { get; set; }

    /// <summary>
    /// Optional narrative body text for this phase node.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Narrative { get; set; }

    /// <summary>
    /// Optional presentation cue effect key used when presenting narrative text.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? NarrativePresentationCueEffectKey { get; set; }

    /// <summary>
    /// Parent phase id. Null indicates root Book tier node.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Guid? ParentPhaseId { get; set; }

    /// <summary>
    /// Ordered child phase ids. Persisted order is canonical traversal order.
    /// </summary>
    public List<Guid> ChildPhaseIds { get; set; } = new();

    /// <summary>
    /// Optional ambience sound effect id for this phase node.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Guid? PhaseAmbientSoundEffectId { get; set; }

    /// <summary>
    /// Optional timer key that drives repeated ambience playback for this phase node.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? PhaseAmbientTimerKey { get; set; }

    /// <summary>
    /// Optional ambience composition mode when this node defines ambience.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.PhaseAmbienceMode? PhaseAmbienceMode { get; set; }

}
