// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file PlanetDto_contract.schema.json.
///
/// Shared Planet contract members used by runtime and designer DTO wrappers.
/// </summary>
internal sealed partial class PlanetDto : DesignerScopeNodeDtoBase
{
    /// <summary>
    /// The starting country when gameplay arrives on this planet.
    /// </summary>
    public string StartingCountryName { get; set; } = string.Empty;

    public List<Guid> CountryIds { get; set; } = new();

}
