// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProcedureParticipantRequirementDto_contract.schema.json.
/// </summary>
internal sealed partial class ProcedureParticipantRequirementDto
{
    public Guid ObjectId { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.ProcedureParticipantMatchKind MatchKind { get; set; } = ContractEnums.ProcedureParticipantMatchKind.ObjectId;

    public string MatchValue { get; set; } = string.Empty;

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.ProcedureParticipantSatisfactionMode SatisfactionMode { get; set; } = ContractEnums.ProcedureParticipantSatisfactionMode.PossessionRequired;

    public int Quantity { get; set; } = 1;

    public bool OptionalPart { get; set; } = false;

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.ProcedureParticipantConsumptionPolicy ConsumptionPolicy { get; set; } = ContractEnums.ProcedureParticipantConsumptionPolicy.None;

    public List<ProjectLockParticipantVariableRequirementDto> VariableRequirements { get; set; } = new();

}
