// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProcedureDefinitionDto_contract.schema.json.
/// </summary>
internal sealed partial class ProcedureDefinitionDto
{
    public Guid Id { get; set; }

    public string Name { get; set; } = string.Empty;

    public string ProcedureSummary { get; set; } = string.Empty;

    public string ProcedureDescription { get; set; } = string.Empty;

    public List<ProcedureParticipantRequirementDto> Participants { get; set; } = new();

    public List<ProcedureParticipantMutationDto> ParticipantMutations { get; set; } = new();

}
