// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectTimerDefinitionDto_contract.schema.json.
///
/// Defines a timer configuration that can be started and canceled by actions.
///
/// Designer-authored timer definition used to configure delayed or repeating action execution.
/// </summary>
internal sealed partial class ProjectTimerDefinitionDto
{
    /// <summary>
    /// Stable timer key used to identify the timer definition and cancel matching scheduled
    /// instances.
    /// </summary>
    public string TimerKey { get; set; } = string.Empty;

    /// <summary>
    /// Delay in milliseconds before the timer first fires after it is started.
    /// </summary>
    public int ScheduleAfterMs { get; set; }

    /// <summary>
    /// Specifies whether the timer fires once or repeats.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.TimerFireMode FireMode { get; set; }

    /// <summary>
    /// Specifies interval progression behavior for repeating timers.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.TimerRepeatMode? RepeatMode { get; set; }

    /// <summary>
    /// Specifies whether repeating interval changes are linear or exponential for growing and
    /// shrinking modes. Linear uses additive step math. Exponential uses multiplicative rate math.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.TimerRepeatProgressionMode? RepeatProgressionMode { get; set; }

    /// <summary>
    /// Base repeat interval in milliseconds used for repeating timers.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? RepeatIntervalMs { get; set; }

    /// <summary>
    /// Step size in milliseconds used for linear progression. For growing timers, effective
    /// interval increases by this step each cycle. For shrinking timers, effective interval
    /// decreases by this step each cycle before min/expiry rules.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? RepeatIntervalStepMs { get; set; }

    /// <summary>
    /// Tuning value for exponential progression. For growing timers, next interval =
    /// round(currentInterval * repeatProgressionRate). For shrinking timers, next interval =
    /// round(currentInterval / repeatProgressionRate) before min/expiry rules. Must be greater than
    /// 1.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? RepeatProgressionRate { get; set; }

    /// <summary>
    /// Minimum repeat interval in milliseconds allowed when shrinking intervals.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? RepeatIntervalMinMs { get; set; }

    /// <summary>
    /// Optional shrink-expiry threshold; when the next shrinking interval would be lower than this
    /// value, the timer expires.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? ShrinkingExpiresUnderMs { get; set; }

    /// <summary>
    /// Action reference executed when the timer fires normally.
    /// </summary>
    public string TargetActionRef { get; set; } = string.Empty;

    /// <summary>
    /// Optional action reference executed once when shrinking expiry is reached.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? OnShrinkExpiryActionRef { get; set; }

    /// <summary>
    /// Owner type used to determine timer lifetime invalidation boundaries.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.TimerOwnerType LifetimeOwnerType { get; set; }

    /// <summary>
    /// Behavior used when starting a timer whose key is already active for the same owner context.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.TimerConflictBehavior ConflictBehavior { get; set; }

    /// <summary>
    /// Indicates whether the timer definition is enabled for scheduling.
    /// </summary>
    public bool Enabled { get; set; }

}
