// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectCommandActionReferenceDto_contract.schema.json.
///
/// Represents one linked-flow node. Each node references the action to execute and declares
/// downstream node ids by branch result.
/// </summary>
internal sealed partial class ProjectCommandActionReferenceDto
{
    /// <summary>
    /// Stable node identifier unique within a single linked-flow payload.
    /// </summary>
    public int NodeId { get; set; }

    /// <summary>
    /// Identifier of the action executed when this node is visited.
    /// </summary>
    public Guid ActionId { get; set; }

    /// <summary>
    /// Downstream node ids that execute regardless of current node success or failure.
    /// </summary>
    public List<int> OnAlwaysNodeIds { get; set; } = new();

    /// <summary>
    /// Downstream node ids that execute when the current node action succeeds.
    /// </summary>
    public List<int> OnSuccessNodeIds { get; set; } = new();

    /// <summary>
    /// Downstream node ids that execute when the current node action fails.
    /// </summary>
    public List<int> OnFailureNodeIds { get; set; } = new();

}
