// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectLockKeyRequirementDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectLockKeyRequirementDto
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Guid ObjectId { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.ProcedureParticipantMatchKind MatchKind { get; set; } = ContractEnums.ProcedureParticipantMatchKind.ObjectId;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? MatchValue { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.ProcedureParticipantSatisfactionMode SatisfactionMode { get; set; } = ContractEnums.ProcedureParticipantSatisfactionMode.PossessionRequired;

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.ProcedureParticipantConsumptionPolicy ConsumptionPolicy { get; set; } = ContractEnums.ProcedureParticipantConsumptionPolicy.None;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool IsOptional { get; set; } = false;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ProjectLockParticipantVariableRequirementDto>? VariableRequirements { get; set; }

    public Guid RequiredObjectId { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public int RequiredQuantity { get; set; } = 1;

}
