// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectObjectImageVariantDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectObjectImageVariantDto
{
    public string VariantName { get; set; } = string.Empty;

    public string FullImagePath { get; set; } = string.Empty;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public double? ImageLocalAlignmentRotationDegrees { get; set; } = 0;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public double? ImageLocalAlignmentOffsetX { get; set; } = 0;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public double? ImageLocalAlignmentOffsetY { get; set; } = 0;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public double? ImageScale { get; set; } = 0;

    public bool IsDefault { get; set; }

}
