// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectGameObjectDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectGameObjectDto : DesignerScopeNodeDtoBase
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Guid? DesignTimeParentObjectId { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public Guid? LinkedBaseObjectId { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool? LinkActionsToBaseObject { get; set; }

    public string ProductionName { get; set; } = string.Empty;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? NameSynonyms { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ProjectObjectImageVariantDto>? ImageVariants { get; set; }

    public double ImageRotationDegrees { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? RenderZOrder { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? AuthoredRenderOrder { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ImageVariantChooserScript { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ProjectGameObjectAppearanceDto? Appearance { get; set; }

    public bool IsInventoriable { get; set; }

    public int InventoryPointsDefaultValue { get; set; } = 1;

    public bool IsContainer { get; set; }

    public int ContainerPointsDefaultValue { get; set; } = 1;

    public bool IsOpenable { get; set; }

    public bool IsOpenDefaultValue { get; set; }

    public bool IsLockable { get; set; }

    public bool IsLockedDefaultValue { get; set; }

    public bool IsActivatable { get; set; }

    public bool IsActiveDefaultValue { get; set; }

    public bool IsHidable { get; set; }

    public bool IsHiddenDefaultValue { get; set; }

    public string Description { get; set; } = string.Empty;

    public bool IsQuantifiable { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Quantity { get; set; } = 1;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.QuantifiablePlacementDistributionMode? QuantifiablePlacementDistributionMode { get; set; } = ContractEnums.QuantifiablePlacementDistributionMode.IndividualInstances;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ProjectLockOperationRequirementsDto? LockOperationRequirements { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ProjectCompositeRecipeDto? CompositeRecipe { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? Commands { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ProjectGameObjectDto>? ContainedObjects { get; set; }

}
