// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectAuthoringRootDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectAuthoringRootDto
{
    public string Name { get; set; } = string.Empty;

    public string FormatVersion { get; set; } = "1.0";

    public string SourceProjectName { get; set; } = string.Empty;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? GameDisplayName { get; set; } = string.Empty;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? GameSummary { get; set; } = string.Empty;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? GamePreviewImages { get; set; }

    public DateTime UpdatedUtc { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? HideEmptyConfiguration { get; set; } = false;

    public int AutoSaveSeconds { get; set; } = 60;

    public int RoomImageCanvasWidth { get; set; } = 800;

    public int RoomImageCanvasHeight { get; set; } = 600;

    public int RoomDesignerGridCellSize { get; set; } = 40;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? StackScaleStepDefault { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? MinStackScaleDefault { get; set; }

    public string SimulatorReplayFilePath { get; set; } = string.Empty;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? SimulatorReplaySpeed { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.AreaAdjacencyMode DefaultTraversalMode { get; set; } = ContractEnums.AreaAdjacencyMode.FourDirectional;

    public List<string> ProjectIgnoredValidationRuleIds { get; set; } = new();

    public List<string> GlobalIgnoredValidationRuleIds { get; set; } = new();

    public List<string> ObjectTemplatesIgnoredValidationRuleIds { get; set; } = new();

    public List<string> RoomTemplatesIgnoredValidationRuleIds { get; set; } = new();

    public List<string> BaseObjectsIgnoredValidationRuleIds { get; set; } = new();

    public string StartingPlanetName { get; set; } = string.Empty;

    public string PlayerCharacterObjectName { get; set; } = string.Empty;

    public List<string> PlayerIgnoredValidationRuleIds { get; set; } = new();

}
