// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectLockOperationRequirementsDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectLockOperationRequirementsDto
{
    public List<ProjectLockKeyRequirementDto> UnlockKeyRequirements { get; set; } = new();

    public bool RequireKeyForLockOperation { get; set; } = true;

    public bool UseUnlockKeysForLockOperation { get; set; } = true;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ProjectLockKeyRequirementDto>? LockKeyRequirements { get; set; }

}
