// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectLockParticipantVariableRequirementDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectLockParticipantVariableRequirementDto
{
    public string VariableName { get; set; } = string.Empty;

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.RuntimeVariableComparisonOperator Operator { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ExpectedValue { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.RuntimeVariableQuantityEvaluationMode QuantityEvaluationMode { get; set; }

}
