// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectEventSubscriptionDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectEventSubscriptionDto
{
    public Guid Id { get; set; }

    public string EventKey { get; set; } = string.Empty;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SubscriptionName { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? IsEnabled { get; set; } = true;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Lane { get; set; } = "foreground";

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.EventSubscriberDispatchDisposition? DispatchDisposition { get; set; } = ContractEnums.EventSubscriberDispatchDisposition.bubble;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? SubscriptionVisibleWhenContained { get; set; } = false;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.SubscriptionSourceMatchMode? SubscriptionSourceMatchMode { get; set; } = ContractEnums.SubscriptionSourceMatchMode.AnySource;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Guid? SubscriptionSourceScopeNodeId { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.SubscriptionSourceMatchMode? SubscriptionSecondarySourceMatchMode { get; set; } = ContractEnums.SubscriptionSourceMatchMode.AnySource;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Guid? SubscriptionSecondarySourceScopeNodeId { get; set; }

    public List<ProjectEventActionBindingDto> ActionBindings { get; set; } = new();

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<ProjectEventInputArgumentMappingDto>? InputArgumentMappings { get; set; }

}
