// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file RoomImageDto_contract.schema.json.
/// </summary>
internal sealed partial class RoomImageDto
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.RoomImageSlot Slot { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool UseDefaultImage { get; set; } = false;

    public int OverlayRenderOrder { get; set; } = 150;

    public double OverlayOffsetX { get; set; }

    public double OverlayOffsetY { get; set; }

    public double OverlayRotationDegrees { get; set; }

    public string FullImagePath { get; set; } = string.Empty;

    public string GrayMapImagePath { get; set; } = string.Empty;

    public string NormalMapImagePath { get; set; } = string.Empty;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? DisplayMode { get; set; }

}
