// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file RoomDto_contract.schema.json.
/// </summary>
internal sealed partial class RoomDto : DesignerScopeNodeDtoBase
{
    public string Description { get; set; } = string.Empty;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? RoomImageCanvasWidth { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? RoomImageCanvasHeight { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.RuntimeRoomImageDisplayMode RoomDisplayMode { get; set; } = ContractEnums.RuntimeRoomImageDisplayMode.Overlay;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ProducerNotes { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TraversalModeOverride { get; set; }

    public List<RoomImageDto> Images { get; set; } = new();

}
