// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file RoomPlacementDto_contract.schema.json.
/// </summary>
internal sealed partial class RoomPlacementDto
{
    public Guid RoomId { get; set; }

    public double X { get; set; }

    public double Y { get; set; }

    /// <summary>
    /// Map floor placement for the room: 0 is ground level, positive is above ground, negative is
    /// below ground.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? FloorElevation { get; set; } = 0;

}
