// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// SoundEffectLibraryEntryDto_contract.schema.json.
///
/// Shared sound-effect library entry used by both designer authoring and runtime cue resolution.
/// </summary>
internal sealed partial class SoundEffectLibraryEntryDto
{
    /// <summary>
    /// Stable immutable GUID identifier used by internal references and mappings.
    /// </summary>
    public Guid SoundEffectId { get; set; }

    /// <summary>
    /// Stable readable key used for diagnostics and author-facing identification. Must be globally
    /// unique within the project.
    /// </summary>
    public string SoundEffectKey { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable label shown in authoring tools when selecting a sound effect.
    /// </summary>
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>
    /// Optional grouping label used for browsing and filtering in sound library UX.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Category { get; set; }

    /// <summary>
    /// Host-resolvable asset key for the sound resource; avoids machine-specific absolute paths.
    /// </summary>
    public string AssetRef { get; set; } = string.Empty;

    /// <summary>
    /// Playback lane hint used by hosts to route emitted cues for this sound effect.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.SoundEffectLane SoundEffectLane { get; set; } = ContractEnums.SoundEffectLane.Sfx;

    /// <summary>
    /// Optional playback gain override in decibels. Use null or omit to preserve source/default
    /// playback level with no authored gain override. A value of 0 means unchanged level, negative
    /// values attenuate, and positive values amplify.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public double? BaseVolumeDb { get; set; }

    /// <summary>
    /// Optional fade-in duration in milliseconds for each play instance. A value of 0 or null means
    /// no fade-in ramp.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? FadeInMs { get; set; }

    /// <summary>
    /// Optional fade-out duration in milliseconds at the end of each play instance. A value of 0 or
    /// null means no fade-out ramp.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? FadeOutMs { get; set; }

    /// <summary>
    /// Playback repeat strategy: None plays once, RepeatForDuration repeats until repeatDurationMs
    /// cap, RepeatCount repeats a fixed number of times, and UntilCanceled repeats indefinitely
    /// until an explicit cancel cue is emitted.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.SoundEffectRepeatMode RepeatMode { get; set; } = ContractEnums.SoundEffectRepeatMode.None;

    /// <summary>
    /// Playback admission policy for replay requests when the same sound effect may already be
    /// active.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.SoundEffectReplayPolicy ReplayPolicy { get; set; } = ContractEnums.SoundEffectReplayPolicy.PlayAgain;

    /// <summary>
    /// Optional repeat count used when repeatMode is RepeatCount; ignored for None,
    /// RepeatForDuration, and UntilCanceled.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? RepeatCount { get; set; }

    /// <summary>
    /// Optional delay in milliseconds before first playback starts after the cue is triggered.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? StartDelayMs { get; set; }

    /// <summary>
    /// Optional delay in milliseconds between repeat iterations when repeating.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? RepeatIntervalMs { get; set; }

    /// <summary>
    /// Authored source duration in milliseconds used for runtime playback planning when no explicit
    /// maxPlayDurationMs cap is provided.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? DurationMs { get; set; }

    /// <summary>
    /// Optional maximum duration in milliseconds for a single play instance. In RepeatCount mode,
    /// this cap applies to each individual play, not to the total repeated cycle.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? MaxPlayDurationMs { get; set; }

    /// <summary>
    /// Optional total repeat duration in milliseconds used when repeatMode is RepeatForDuration.
    /// Ignored for None, RepeatCount, and UntilCanceled modes.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? RepeatDurationMs { get; set; }

    /// <summary>
    /// Optional repeat retrigger suppression window in milliseconds that prevents immediate
    /// repeat-cycle replay spam.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? RepeatCooldownMs { get; set; }

    /// <summary>
    /// Optional group key for host polyphony policy, such as single-instance or replacement
    /// behavior within a group.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ConcurrencyGroup { get; set; }

    /// <summary>
    /// Optional in-group importance rank used to arbitrate contention among sounds that compete
    /// within the same concurrency group. Higher values are more important and lower values are
    /// less important.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? ConcurrencyGroupImportance { get; set; }

    /// <summary>
    /// Optional global importance rank used when host-level resource limits require dropping sounds
    /// across groups. Higher values are more important and lower values are less important.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Importance { get; set; }

}
