// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// TraversalConnectionDto_contract.schema.json.
///
/// Represents a connection between two rooms in an area, represents both directions of the travel.
/// This is designer centric and not used directly by the runtime.
/// </summary>
internal sealed partial class TraversalConnectionDto
{
    public Guid TraversalConnectionId { get; set; }

    public Guid RoomAId { get; set; }

    public Guid RoomBId { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.Direction10 BaseTraversalDirectionFromA { get; set; } = ContractEnums.Direction10.North;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.AreaAdjacencyMode? TraversalModeOverride { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.TraversalAccessMode TraversalAccessMode { get; set; } = ContractEnums.TraversalAccessMode.TwoWay;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? PresentationEffectKey { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TraversalLegStateDto? TraversalStateFromA { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TraversalLegStateDto? TraversalStateFromB { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ContractEnums.OpenStateBindingMode? OpenStateBindingMode { get; set; } = ContractEnums.OpenStateBindingMode.Independent;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<GamePropertyDefinitionDto>? GameProperties { get; set; }

}
