using StoryboardDesigner.App.Models;
using StoryboardDesigner.App.ViewModels;
using Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

public sealed record ObjectBasicPropertiesEditRequest(
    string Name,
    string NameInGame,
    string ProducerNotes,
    bool IsInventoriable,
    int InventoryPointsDefaultValue,
    bool IsContainer,
    int ContainerPointsDefaultValue,
    bool IsCapacityPointShareDividerEnabled,
    int CapacityPointShareDividerDefaultValue,
    bool IsOpenable,
    bool IsOpenDefaultValue,
    bool IsLockable,
    bool IsLockedDefaultValue,
    bool IsActivatable,
    bool IsActiveDefaultValue,
    bool IsHidable,
    bool IsHiddenDefaultValue,
    bool IsQuantifiable,
    int Quantity,
    string QuantifiablePlacementDistributionMode,
    bool IsCompositeTarget,
    bool IsCompositeReversible,
    string CompositePartRequirementMode,
    int CompositeMinimumRequiredPartCount,
    List<Guid> CompositeRequiredPartObjectIds,
    IReadOnlyList<GameObjectSelectionOption> AvailableCompositePartOptions,
    string Description,
    string FullImagePath = "",
    double ImageRotationDegrees = 0,
    string ProjectFilePath = "",
    string PreferredImageSourceBucket = "objects",
    string LinkedEditNotice = "",
    IReadOnlyList<ObjectImageVariant>? ImageVariants = null,
    string ImageVariantChooserScript = "",
    IReadOnlyList<string>? ImageVariantChooserReferenceTokens = null,
    IReadOnlyList<GamePropertyChoiceItem>? ImageVariantChooserVariableChoices = null,
    PropertyResolutionScope ImageVariantChooserVariableScope = PropertyResolutionScope.Object,
    LockOperationRequirements? LockOperationRequirements = null,
    IReadOnlyList<GameObjectSelectionOption>? AvailableLockKeyOptions = null,
    List<CompositePartRequirement>? CompositeRequiredParts = null,
    string ObjectNameSynonyms = "",
    bool IsMovable = false,
    bool IsMovableDefaultValue = true,
    RuntimeObjectSpatialTypes SpatialType = RuntimeObjectSpatialTypes.SolidObject,
    int StackGroup = 0,
    int FootprintWidthCells = 1,
    int FootprintHeightCells = 1,
    string FootprintOrientation = "N",
    string HeadingDirection = "N",
    int ObjectHeightUnits = 1,
    int HeightInRoom = 0,
    double? StackScaleStepOverride = null,
    double? MinStackScaleOverride = null,
    ObjectMovementRestrictions? MovementRestrictions = null,
    int ProjectRoomGridCellSize = 40,
    int ProjectRoomCanvasWidth = 800,
    int ProjectRoomCanvasHeight = 600,
    string LinkedBaseObjectName = "");
