// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectSetPhaseActionPayloadDto_contract.schema.json.
///
/// Payload for direct phase jump targeting by producer-defined phase key.
/// </summary>
internal sealed partial class ProjectSetPhaseActionPayloadDto : ProjectCommandActionPayloadBaseDto
{
    public string PhaseKey { get; set; } = string.Empty;

}
