// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectBuildCompositeByPartsActionPayloadDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectBuildCompositeByPartsActionPayloadDto : ProjectCommandActionPayloadBaseDto
{
    public Guid CompositeTargetObjectId { get; set; }

    public Guid CompositeRecipeId { get; set; }

    public List<Guid> CompositeRequiredPartObjectIds { get; set; } = new();

    public bool CompositeStrictPartCountEnforcement { get; set; }

    public int CompositeMinimumRequiredPartCount { get; set; }

    public string CompositeMatchMode { get; set; } = string.Empty;

    public string CompositeAmbiguityPolicy { get; set; } = string.Empty;

    public string CompositePartConsumptionMode { get; set; } = string.Empty;

}
