// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectMoveRoomObjectOnGridActionPayloadDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectMoveRoomObjectOnGridActionPayloadDto : ProjectCommandActionPayloadBaseDto
{
    public string DirectionToken { get; set; } = string.Empty;

    public int DistanceInCells { get; set; }

    public bool AllowPartialMove { get; set; }

    public bool AllowJumpOver { get; set; }

    public string VisualTransitionHint { get; set; } = string.Empty;

    public string TravelVisualizationMode { get; set; } = string.Empty;

}
