// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectLinkedFlowActionPayloadDto_contract.schema.json.
///
/// Node-based linked action flow. The first element in linkedActions is the entry/root node;
/// subsequent traversal is determined only by each node's
/// onAlwaysNodeIds/onSuccessNodeIds/onFailureNodeIds.
/// </summary>
internal sealed partial class ProjectLinkedFlowActionPayloadDto : ProjectCommandActionPayloadBaseDto
{
    /// <summary>
    /// All linked-flow nodes for this action payload. Node ids must be unique within this list.
    /// </summary>
    public List<ProjectCommandActionReferenceDto> LinkedActions { get; set; } = new();

}
