// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectCancelSoundEffectActionPayloadDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectCancelSoundEffectActionPayloadDto : ProjectCommandActionPayloadBaseDto
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Guid? PlayRequestInstanceId { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? EffectKey { get; set; }

}
