// <auto-generated>
// This file is generated from RuntimeContracts/Schemas/*_contract.schema.json by Storyboard.SchemaCodegen.
// Do not edit this file directly. Update schema + codegen inputs, then regenerate and accept.
// </auto-generated>
#nullable enable

using System.Text.Json.Serialization;
using ContractEnums = Storyboard.Shared.RuntimeContracts.Enums;

namespace StoryboardDesigner.App.Services;

/// <summary>
/// This is a schema backed contract dto from the schema file
/// ProjectRotateRoomObjectOnGridActionPayloadDto_contract.schema.json.
/// </summary>
internal sealed partial class ProjectRotateRoomObjectOnGridActionPayloadDto : ProjectCommandActionPayloadBaseDto
{
    public string Mode { get; set; } = string.Empty;

    public int TurnDegrees { get; set; }

    public string FacingDirectionToken { get; set; } = string.Empty;

    public string VisualTransitionHint { get; set; } = string.Empty;

}
